"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7'th triangle number would be
1 + 2 +...+ 7 = 28
The first ten terms would be: 1,3,6,10,15,21,28,36,45,55

We can see that _28_ is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
"""
import math

triangular_nums = [1]
i = 0

def n_factors(k):
    return k

while not (n_factors(triangular_nums[i]) > 500):
    i += 1
    n = triangular_nums[i-1] + i+1
    triangular_nums.append(n) # prev num + curr natural num
    print(f"{i}: {n}") # ljust n??

print(f"1st triangle num n with divisors k > 500: {triangular_nums[-1]}")

