# Even Fibonacci Numbers

import numpy as np

"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1,2,3,5,8,13,21,34,55,89

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
fib_seq = [1,2]
a=1
b=2
n=3
while n <= 4000000:
    fib_seq.append(n)
    a=b
    b=n
    n=a+b

sum_of_evens = 0
for i in range(len(fib_seq)):
    if fib_seq[i] % 2 == 0:
        sum_of_evens += fib_seq[i]

print(sum_of_evens)
